### ISSUE TITLE
Error cauing tax issues with line Items

### ISSUE THREAD

**Issue by deanfields** [KuriousAgency/commerce-bulk-pricing#10]
https://github.com/KuriousAgency/commerce-bulk-pricing/blob/fb397c230a45114ff205c07506eac7c610d681b5/src/adjusters/Tax.php#L187

This line is causing a bug where the tax isn't being discounted on each line, only removing the VAT off one line item.

Tested removing this line which seemed to fix the issue

**Comment by terryupton** [comment]
I am seeing this issue too. Can we get an official release that fixes this @samuelbirch ?

**Comment by terryupton** [comment]
Here are some screenshots to support this.
<img width="1038" alt="Screenshot 2022-04-14 at 10 53 29" src="https://user-images.githubusercontent.com/5698596/163362907-e8f48948-48d5-42df-add8-dfd9f8b983f0.png">
<img width="1026" alt="Screenshot 2022-04-14 at 10 48 55" src="https://user-images.githubusercontent.com/5698596/163362918-cde801b6-5f09-40d2-a3dc-1286d3041b46.png">

**Comment by terryupton** [comment]
> https://github.com/KuriousAgency/commerce-bulk-pricing/blob/fb397c230a45114ff205c07506eac7c610d681b5/src/adjusters/Tax.php#L187
> 
> This line is causing a bug where the tax isn't being discounted on each line, only removing the VAT off one line item.
> 
> Tested removing this line which seemed to fix the issue

@deanfields has this continued to function ok since you updated this in November?

**Comment by mcjackson18** [comment]
Hi @terryupton, @deanfields, the above change has been made in version 1.1.7.
