### ISSUE TITLE
Is this plugin suitable to work with variants?

### ISSUE THREAD

**Issue by terryupton** [KuriousAgency/commerce-bulk-pricing#2]
Is this plugin aimed at single commerce products or would this work with variant options? 
Thanks,

**Comment by samuelbirch** [comment]
Hi, 
Yes this plugin will work with variants.

**Comment by terryupton** [comment]
ok, I am having trouble getting it to apply discounts for variants or products.
Are there are more detailed docs somewhere or any chance we could grab 5 minutes of Craft Discord?

Thanks,

**Comment by terryupton** [comment]
Is this plugin for Craft Commerce 1 or Craft Commerce 2?

**Comment by samuelbirch** [comment]
This is for Commerce 2.

Feel free to grab me on Discord or you can email me a database and composer.json and i'll take a look?

**Comment by terryupton** [comment]
Hey @samuelbirch - be good to grab five on Discord if we can?
What is your alias?

**Comment by samuelbirch** [comment]
my alias should be samuelbirch

**Comment by samuelbirch** [comment]
update: problem was no user group was selected when setting up the field.
I'll make a change that if no user groups are selected then all users get to see the price change. I'll also add a switch to show to guest users or not.

**Comment by samuelbirch** [comment]
now available in verson 1.1.0
