### ISSUE TITLE
Price doesn't seem to be changing

### ISSUE THREAD

**Issue by dgtlcrftrs** [KuriousAgency/commerce-bulk-pricing#5]
I have a product with a bulk pricing field applied, with the 1, 1 set (so it applies based on group and not quantity). I have a user with the correct group on, but the pricing isn't changing. 

versions:

php 7.3.12

Commerce Bulk Pricing 1.1.0
Commerce Currency Prices 2.6.1
Craft Commerce 2.2.15

**Comment by mcjackson18** [comment]
@dgtlcrftrs please can you confirm if this is linked to the issue you added to commerce-currency-prices and that disabling currency prices resolved this issue?

**Comment by dgtlcrftrs** [comment]
Yes this is linked

**Comment by mcjackson18** [comment]
I'll close this as issue continued here: [Plugin with bulk-pricing is causing problems with the cost](https://github.com/KuriousAgency/commerce-currency-prices/issues/11)
