### ISSUE TITLE
Bulk price not working.

### ISSUE THREAD

**Issue by demoseed** [KuriousAgency/commerce-bulk-pricing#6]
I have create a new field for product bulk price. And then prices added on each product.
Filed: http://prntscr.com/rchd1c
Product: https://prnt.sc/rchbc4

When I have buy this product on bulk quantity ( e.g 5+ ) but in the checkout page price not populate according bulk price. 
http://prntscr.com/rchggs

So anything additional settings require.

**Comment by mikeymeister** [comment]
Hi, this should be fixed in v1.1.2, the item salePrice should now be set by the plugin as well as the item price.
