### ISSUE TITLE
Unable to add new Table Column to Bulk Pricing field

### ISSUE THREAD

**Issue by stevenvandemoortele** [KuriousAgency/commerce-bulk-pricing#8]
Clicking on the "+ Add a column" button in a Bulk Pricing field doesn't work and throws a javascript error.
`Uncaught TypeError: Craft.TableFieldSettings is not a constructor`

PHP version: 7.3.10
Craft edition & version: Craft Pro 3.5.10.1
Craft Commerce: 3.2.6
Commerce Bulk Pricing: 1.1.2

**Comment by stevenvandemoortele** [comment]
Any word on this? Is the plugin still being maintained?

**Comment by malcolmhmaclean** [comment]
Hi there, yes getting the same issue in Craft 3.5.16 - would be great to get it fixed

**Comment by mcjackson18** [comment]
@stevenvandemoortele, @malcolmhmaclean this has now been fixed in version 1.1.3.
